# Generated by Django 6.0.6 on 2026-07-09 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentExcelApp', '0005_historicalstudent_user_id_student_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstudent',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_id',
        ),
    ]
