# Generated by Django 6.0.6 on 2026-07-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentExcelApp', '0006_remove_historicalstudent_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=10),
        ),
    ]
