# Generated by Django 6.0.6 on 2026-07-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentExcelApp', '0007_loginhistory_failure_reason_loginhistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudent',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='institution',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='institution',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
